.TH anysurrect 8 "13 Mar 2007" "Version 0.84.6"
.SH "НАЗВАНИЕ"
anysurrect \- ищет файлы на устройстве и сохраняет полученную информацию \
в файле внешней таблицы инф.узлов.
.SH "СИНТАКСИС"
.nf
.BI "anysurrect [\-b " blocksize "] [\-i " input_inode_table "]"
.BI "	[\-p " path_prefix "] [\-u " file_umask "] [\-U " dir_umask "] [\-fqvV] "
.BI "	[\-g " plug-ins "] [\-e] [\-t" " list_of_types" "] [\-T" " list_of_types" "] "
.BI "	[\-l] " "device inode_table"
.fi

.SH "ОПИСАНИЕ"

.B anysurrect 
ищет на устройстве файлы исходя из известной структуры \
различных типов файлов. Информация о найденных файлах также сохраняется \
в виде внешней таблицы инф.узлов.

.B anysurrect
открывает устройство в режиме только для чтения, поэтому \
данные на нём не будут изменены.

На данный момент
.B anysurrect
поддерживает следующие типы файлов:

.br
изображения:
.BR  PNG ", " JPEG ", " BMP ", " PNM ", " TIFF
.br
звук:
.BR  WAV ", "  MIDI ", " MPEG3
.br
звук и видео:
.BR  OGG ", " AVI ", " "MPEG2 stream" " (при наличии -lmpeg2), " "program multiplex MPEG2 stream"
.br
архивы:
.BR  TAR ", " ZIP ", " RAR ", " BZIP2 " (при наличии -lbzip2), " GZIP
.br
документы:
.BR  PDF
.br
запускаемые:
.BR  ELF32
.br
простой текст:
.BR  ASCII ", " "8-битная кодировка" ", " UTF-8 ", " UTF16-BE ", " UTF16-LE
.br
образы компакт дисков:
.BR  ISO9660 .

Для лучшего восстановления 
.B anysurrect
может распознавать системные блоки следующих файловых систем:

.br
.BR "EXT2FS/EXT3FS:" " блоки DIRECT, INDIRECT и DOUBLE INDIRECT \
ссылками, блоки таблицы инф.узлов (см. описание опции -e)."

При этом поиск текстов является дорогой (в смысле использования \
процессорного времени) операцией. Поэтому по умолчанию распознаются только
.B ASCII
тексты. Список распознаваемых форматов \
может быть изменён опцией 
.IR \-t .
Распознаваемые окончания строк (Unix, DOS и MAC) настраиваются \
на стадии компиляции правкой файла anyfs-tools/src/anysurrect/config.h

Итак поиск файлов утилитой
.B anysurrect
основан на знании внутренней структуры этих файлов. Такой поиск \
не зависит от файловой системы носителя. Однако при этом оригинальные \
имена файлов и структура каталогов теряются.

Некоторые способы восстановления имён файлов демонстрирует пакет
.B anyrename
который также может быть скачан в разделе Download сайта anyfs-tools.

.B anysurrect
не найдёт файлы если они не выровнены по границе блока (например, на
.B ReiserFS
файлы меньше 4 Кб хранятся в таком упакованном формате), \
файлы с tail-packing'ом на Reiser4 или \
если они заархивированы/зашифрованы на_уровне_файловой_системы \
(такую возможность, например, имеет
.BR NTFS " --"
да, конечно, Microsoft не поддерживает Unix-way).

.SH "О ФРАГМЕНТИРОВАННЫХ ФАЙЛАХ"
Экспериментальная реализация восстановления фрагментированных файлов \
показала, что вероятность соединить при этом что-то с чем-то, да не с тем \
слишком высока. Поэтому максимум на что можно надеяться это на использование \
двух-проходного восстановления, когда на первом проходе восстанавливаются \
нефрагментированные файлы, а на втором -- фрагментированные, фрагменты которых \
разделены ранее восстановленными нефрагментированными файлами. \
(при указании опции \-i производится именно такой поиск). \
Но вообще говоря обычно фрагментированных файлов на разделе не столь много, \
чтобы всерьёз об этом беспокоится. \
Восстановление же фрагментированных файлов может быть с бОльшим \
успехом реализовано при попытке поисков файлов по системной информации \
файловой системы (см. описание опций \-e, \-T)
	
.SH "ОПЦИИ"
.TP
.BI \-b " blocksize"
Размер блока файловой системы устройства. Это число должно быть \
степенью двойки, и не меньше 512. По умолчанию принимается равным 512 \
(и может быть увеличено для больших устройств)
.TP
.BI \-i " input_inode_table"
Входящий файл внешней таблицы инф.узлов, вероятно полученный \
применением утилиты
.BR build_it .
При указании этой опции поиск будет производится только по свободным блокам \
устройства. Разумеется, если есть возможность (если файловая система не бита \
и нужно восстановить удалённые файлы) надо пользоваться этой опцией.
.TP
.BI \-p " path_prefix"
Префикс к путям для создаваемых файлов. \
Полезно при использовании совместно с опцией \-i когда в корне уже \
достаточно директорий, чтобы переместить все восстанавливаемые файлы в другую \
более удобную для вас директорию.
.TP
.BI \-u " file_umask"
Восьмеричная маска сбрасываемых прав доступа для файлов. По умолчанию это 002, \
т.е. по умолчанию для создаваемых файлов не даётся прав записи для \
остальных пользователей (не пользователя файла и пользователей не состоящих \
в группе файла).
.TP
.BI \-U " dir_umask"
Аналогично
.B \-u
но для директорий.
.TP
.B \-f
По умолчанию нулевой блок помечается занятым (т.к. обычно там содержится \
суперблок файловой системы) и не просматривается. Эта опция позволяет \
пометить нулевой блок свободным. Вызов `anysurrect -qvf <файл> /dev/null` \
удобно использовать для теста anysurrect на то найдёт ли он конкретный файл.
.TP
.B \-q
Не выводить ни каких сообщений.
.TP
.B \-v
Выводить типы найденных файлов, их начальный блок и размер.
.TP
.B \-V
Вывести только номер версии и выйти.
.TP
.BI \-g " plug-ins"
Начиная с версии 0.83.2
.B anysurect
поддерживает дополнительную загрузку динамических библиотек \
для восстановления новых типов файлов. Перечислите \
подгружаемые библиотеки через пробел. Для списка всех известных типов файлов \
используйте опцию
.IR \-l .
Для включения новых типов файлов в список восстанавливаемых используйте \
опцию
.IR \-t .
.TP
.B \-e
Эквивалентно
.br
.BI \-t " ""filesystem_info_ext2fs_direct_blocks_links filesystem_info_ext2fs_double_indirect_blocks_links filesystem_info_ext2fs_indirect_blocks_links filesystem_info_ext2fs_inode_table"""
.br
При этом anysurrect будет пытаться использовать информацию из найденных блоков,
и будет вызывать surrecter'ы из списка \-T чтобы найти другие файлы.
Распознанные таким образом файлы будут помещены в директорию 
/filesystem_files. При этом, при известном размере файла (если эта информация
найдена в таблице инф.узлов), но не опознанном типе ни одним из surrecter'ов
файл будет помещён в директорию /filesystem_files/UNKNOWN.
Для достижения максимального эффекта при восстановлении с EXT2FS/EXT3FS \
используйте восстановление в два прохода:
.br
1) сначала с опцией \-e, и указанием РЕАЛЬНОГО размера блока опцией \-b \
(и опцией \-i при предварительном использовании
.BR build_it )
.br
2) затем с передачей опцией \-i полученной таблицы инф.узлов в первом пункте
.TP
.BI \-t " list_of_types"
Начиная с версии 0.83.2 вы можете изменять список восстанавливаемых файлов \
без перекомпиляции -- просто перечислите их через пробел в этой опции. \
Для списка поддерживаемых типов файлов используйте опцию
.IR \-l .
.TP
.BI \-T " list_of_types"
Эта опция впервые появилась в версии 0.84.6 пакета. \
Опция задаёт вторичный список восстанавливаемых типов файлов и \
может быть использован совместно с опцией \-e для задания типов файлов \
которые будут искаться с использованием системной информацией ФС.
.TP
.B \-l
Выдаёт полный список известных типов файлов для восстановления.
.TP
.I device
Устройство (или простой файл, образ устройства) для восстановления файлов.
.TP
.I inode_table
Файл, в который будет сохранена сформированная внешняя таблица инф.узлов.

.SH "ПРИМЕРЫ ИСПОЛЬЗОВАНИЯ"
Восстановление из /dev/hda1 в inode.table:
.br
$ anysurrect /dev/hda1 inode.table

Поиск системной информации ext2fs/ext3fs (4096 это обычный размер блока \
ext2fs/ext3fs):
.br
$ anysurrect -b 4096 -e /dev/hda2 inode.table

Восстановление jpeg и png файлов из /dev/hda2 используя \
таблицу инф.узлов из предыдущей стадии:
.br
$ anusurrect -i inode.table -t "image_JPEG image_PNG" /dev/hda2 inode.table

Замечание: так как anysurrect считывает всю информацию из входящей таблицы \
инф.узлов сразу перед поиском, вы можете использовать тот же исходящий файл, \
что и входящий (впрочем как и различные, как в следующем примере).

Восстановление с использованием таблицы инф.узлов полученной
.B build_it
и помещением новых файлов в директорию ANYSURRECT:
.br
$ anusurrect -i inode.table -p "/ANYSURRECT/" /dev/hda3 inode.table2

Замечание: последний слеш в префиксе пути необходим. Иначе будут созданы \
директории с названиями вроде "ANYSURRECTarchieve", "ANYSURRECTimage", \
но в корневой директории.

.SH "АВТОР"
Николай Кривченков aka unDEFER <undefer@gmail.com>

.SH "СООБЩЕНИЯ ОБ ОШИБКАХ"
Сообщения о любых проблемах с применением пакета
.B anyfs-tools
направляйте по адресу:
undefer@gmail.com

.SH "ДОСТУПНОСТЬ"
последнюю версию пакета вы можете получить на сайте проекта: \
http://anyfs-tools.sourceforge.net

.SH "СМ. ТАКЖЕ"
.BR anyfs-tools(8),
.BR anyfs_inode_table(5),
.BR anysurrect-plugins(3)
