.TH build_it 8 "08 Aug 2006" "Version 0.84.5"
.SH "НАЗВАНИЕ"
build_it \- считывает информацию о расположении информационных узлов и \
правах доступа и сохраняет её в файл внешней таблицы инф.узлов.
.SH "СИНТАКСИС"
.BI "build_it [\-qvVn] " "directory inode_table"

.SH "ОПИСАНИЕ"

.B build_it 
считывает из директории рекурсивно информацию обо всех \
инф.узлах файловой системы используя драйвер (для чтения) ОС 
.B Linux
и сохраняет её в виде внешней таблицы инф.узлов.

Для работы утилита требует наличия драйвера файловой системы \
(возможно только для чтения) для ОС 
.B Linux
с поддержкой системного вызова
.BR ioctl (2)
.BR FIBMAP .
Вызов
.B FIBMAP
требует наличия у пользователя прав
.BR суперпользователя .

Работа утилиты протестирована на файловых системах:
.BR EXT2FS/EXT3FS , " XFS" , " ReiserFS" , " VFAT" , " JFS" , " ISO9660" , " NTFS" .

Большинство из них (кроме
.BR NTFS )
имеют полноценную поддержку
.BR FIBMAP .
В драйвере файловой системы
.B NTFS
поддержка
.B FIBMAP
отсутствует вовсе. В связи с этим был направлен запрос такой поддержки:

http://forum.linux-ntfs.org/viewtopic.php?t=58

Если Вас интересует возможность восстановления файлов с
.B NTFS
или конвертирование её в другие файловые системы, то можете поддержать \
этот запрос.

Для
.BR ReiserFS "(и " Reiser4 )
.B build_it
будет вызывать ioctl вызов UNPACK, чтобы избежать tail-packing'а \
и получить правильную карту его файлов.

Вы можете использовать опцию
.B -n
если не хотите изменений на файловой системе (что может быть важно при \
восстановлении данных), но в этом случае вы можете получить не совсем \
верную таблицу инф.узлов.

.SH "ОПЦИИ"
.TP
.B \-q
Не выводить ни каких сообщений.
.TP
.B \-v
Выводить некоторую дополнительную информацию.
.TP
.B \-V
Вывести только номер версии и выйти.
.TP
.B \-n
Не распаковывать файлы ReiserFS и Reiser4FS.
.TP
.I directory
Директория, обычно корень/точка монтирования файловой системы, построение \
таблицы инф.узлов которой будет производится.
.TP
.I inode_table
Файл, в который будет сохранена внешняя таблица инф.узлов.

.SH "ПРИМЕРЫ ИСПОЛЬЗОВАНИЯ"
Построение внешней таблицы инф.узлов файловой системы на устройстве \
смонтированной в домашней директории пользователя user:
.br
# build_it /home/user /tmp/inode.table

Замечание: будет лучше, если будущая таблица инф. узлов будет располагаться \
на другом устройстве (или директории расположенной вне рекурсивной обработки \
дерева), как и в примере.

Замечание: если точка монтирования в этом примере /home (не /home/user) \
то построенная внешняя таблица инф.узлов не будет включать файлов из \
других директорий, чем /home/user -- это будет частичная таблица инф.узлов \
устройства.

Замечание: если там будет другая точка монтирования в рекурсивно обрабатываемом \
дереве (например /home/user/mount/point) -- она не будет обработана \
(таблица инф.узлов не может содержать информации о нескольких различных \
 устройствах)

.SH "АВТОР"
Николай Кривченков aka unDEFER <undefer@gmail.com>

.SH "СООБЩЕНИЯ ОБ ОШИБКАХ"
Сообщения о любых проблемах с применением пакета
.B anyfs-tools
направляйте по адресу:
undefer@gmail.com

.SH "ДОСТУПНОСТЬ"
последнюю версию пакета вы можете получить на сайте проекта: \
http://anyfs-tools.sourceforge.net

.SH "СМ. ТАКЖЕ"
.BR anyfs-tools(8),
.BR ioctl(2),
.BR ioctl_list(2) ,
.BR anyfs_inode_table(5)
