install: 
	$(MAKE) $(AM_MAKEFLAGS) -C ru install
	$(MAKE) $(AM_MAKEFLAGS) -C man3 install
	$(MAKE) $(AM_MAKEFLAGS) -C man5 install
	$(MAKE) $(AM_MAKEFLAGS) -C man8 install

uninstall:
	$(MAKE) $(AM_MAKEFLAGS) -C ru uninstall
	$(MAKE) $(AM_MAKEFLAGS) -C man3 uninstall
	$(MAKE) $(AM_MAKEFLAGS) -C man5 uninstall
	$(MAKE) $(AM_MAKEFLAGS) -C man8 uninstall
